// src/data.js
export const projects = [
    {
      id: 1,
      title: 'AI-Powered Search',
      team: 'Development',
      startDate: 'Oct 1',
      endDate: 'Dec 15',
      status: 'Open',
      insights: 'Potential delay detected in UI Development phase',
      availability: { dev: '3/5', design: '2/3', da: '4/4' },
    },
    {
      id: 2,
      title: 'User Authentication',
      team: 'Design',
      startDate: 'Sep 15',
      endDate: 'Nov 30',
      status: 'At-Risk',
      insights: 'Backend integration completed ahead of schedule',
      availability: { dev: '3/5', design: '2/3', da: '4/4' },
    },
    {
      id: 3,
      title: 'Payment Gateway',
      team: 'Marketing',
      startDate: 'Aug 1',
      endDate: 'Oct 30',
      status: 'Blocked',
      insights: 'New team velocity metrics available',
      availability: { dev: '3/5', design: '2/3', da: '4/4' },
    },
    {
      id: 4,
      title: 'Analytics Dashboard',
      team: 'Development',
      startDate: 'Oct 15',
      endDate: 'Dec 30',
      status: 'Open',
      insights: 'Potential delay detected in UI Development phase',
      availability: { dev: '3/5', design: '2/3', da: '4/4' },
    },
    {
      id: 5,
      title: 'Mobile App Redesign',
      team: 'Design',
      startDate: 'Nov 1',
      endDate: 'Jan 15',
      status: 'At-Risk',
      insights: 'Backend integration completed ahead of schedule',
      availability: { dev: '3/5', design: '2/3', da: '4/4' },
    },
    {
      id: 6,
      title: 'API Integration',
      team: 'Marketing',
      startDate: 'Sep 1',
      endDate: 'Nov 15',
      status: 'On-Track',
      insights: 'New team velocity metrics available',
      availability: { dev: '3/5', design: '2/3', da: '4/4' },
    },
  ];